"""initial

Revision ID: 1b9882f811df
Revises: 
Create Date: 2026-01-29 17:25:09.056073

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9882f811df'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.CheckConstraint('level >= 1 AND level <= 3', name='ck_activities_level_1_3'),
    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_activities_parent_name')
    )
    op.create_index('ix_activities_name', 'activities', ['name'], unique=False)
    op.create_index('ix_activities_parent_id', 'activities', ['parent_id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buildings_address', 'buildings', ['address'], unique=False)
    op.create_index('ix_buildings_lat_lon', 'buildings', ['latitude', 'longitude'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organizations_building_id', 'organizations', ['building_id'], unique=False)
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_table('organization_activities',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'activity_id')
    )
    op.create_index('ix_org_activities_activity_id', 'organization_activities', ['activity_id'], unique=False)
    op.create_index('ix_org_activities_organization_id', 'organization_activities', ['organization_id'], unique=False)
    op.create_table('organization_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'phone', name='uq_org_phones_org_phone')
    )
    op.create_index('ix_org_phones_organization_id', 'organization_phones', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_org_phones_organization_id', table_name='organization_phones')
    op.drop_table('organization_phones')
    op.drop_index('ix_org_activities_organization_id', table_name='organization_activities')
    op.drop_index('ix_org_activities_activity_id', table_name='organization_activities')
    op.drop_table('organization_activities')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_index('ix_organizations_building_id', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_buildings_lat_lon', table_name='buildings')
    op.drop_index('ix_buildings_address', table_name='buildings')
    op.drop_table('buildings')
    op.drop_index('ix_activities_parent_id', table_name='activities')
    op.drop_index('ix_activities_name', table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
